### ISSUE TITLE
failing on https://{url_prefix}.tiktok.com/api/v1/web/project/post/?aid=1988

### ISSUE THREAD

**Issue by wazofski** [546200350/TikTokUploder#38]
For some reason the URL returns 200 but content is empty...

Traceback (most recent call last):
  File "/github/TikTokUploder/uploader.py", line 120, in <module>
    uploadVideo(args.session_id, args.path, args.title, args.tags, args.users, args.url_server)
  File "/github/TikTokUploder/uploader.py", line 98, in uploadVideo
    if r.json()["status_code"] == 0:
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by andersonlthome** [comment]
Same here, the Post returns 200 but nothing happened, the video was not posted.

**Comment by ViktorKravtsov** [comment]
@wazofski @andersonlthome read this: https://github.com/546200350/TikTokUploder/issues/36
