### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#70]
Hello, could someone help me with this error please?

`Traceback (most recent call last):
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 454, in send
    conn = self.get_connection(request.url, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 343, in get_connection
    proxy = prepend_scheme_if_needed(proxy, "http")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 993, in prepend_scheme_if_needed
    parsed = parse_url(url)
             ^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://ip:port

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nathan\Documents\RSL\index.py", line 255, in <module>
    uploadVideo(session_id, file, title, tags, users, proxy=proxy)
  File "C:\Users\Nathan\Documents\RSL\uploader.py", line 29, in uploadVideo
    r = session.get(url, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 456, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Failed to parse: https://ip:port`

**Comment by XavierZambrano** [comment]
You must replace `ip` and `port` with the ip and port of your proxy, a proxy is like: 107.1.93.218:80

**Comment by Fabien-desablens** [comment]
my code:
                proxy = None
                uploadVideo(sessions[account], file_path, title, tags, Users, proxy=proxy)
