### ISSUE TITLE
KeyError: 'Result' and InvalidSecretToken

### ISSUE THREAD

**Issue by kenaubry** [546200350/TikTokUploder#87]
Hi,

I'm encountering a `KeyError: 'Result'` when running the project, and while debugging, I see that it's caused by the line `r = session.get(f"{url}?{request_parameters}", headers=headers)` which returns an `InvalidSecretToken`.

I'm certain that my sessionId is correct.

Do you have any idea how to resolve this issue?

```
...
...
============Start uploading video===========

r.json :
{"ResponseMetadata":{"RequestId":"20240201141608D3A9FF5E52ED37A4115A","Action":"ApplyUploadInner","Version":"2020-11-19","Service":"vod","Region":"ap-singapore-1","Error":{"CodeN":100026,"Code":"InvalidSecretToken","Message":"Invalid secret token, msg: %s."}}}


Traceback (most recent call last):
  File "./TikTokUploader/uploader.py", line 167, in <module>
    uploadVideo(args.session_id, args.path, args.title, args.tags, args.users, args.url_server, args.schedule_time)
  File "./TikTokUploader/uploader.py", line 76, in uploadVideo
    video_id = uploadToTikTok(video, session)
  File "/home/kenza/Desktop/Tiktok/Automation/TikTokUploder/TikTokUploader/util.py", line 147, in uploadToTikTok
    upload_node = r.json()["Result"]["InnerUploadAddress"]["UploadNodes"][0]
KeyError: 'Result'
```

**Comment by matheusfterra** [comment]
same error here

**Comment by wdoer** [comment]
get it half year ago))

Idk how fix that ;c

**Comment by Jamadoo** [comment]
Tiktok changed their josn response. If anyone could figure out where it is stored now, itd be great.

**Comment by 546200350** [comment]
fixed
