### ISSUE TITLE
Video don't get upload

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#90]
Hi, I'm getting this error, could someone help me please?

`Traceback (most recent call last):
  File "/Users/nathan/Documents/RSL/index.py", line 253, in <module>
    uploadVideo(session_id, file, title, tags, users, url_prefix, proxy=proxy)
  File "/Users/nathan/Documents/RSL/uploader.py", line 56, in uploadVideo
    video_id = uploadToTikTok(video, session)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nathan/Documents/RSL/util.py", line 146, in uploadToTikTok
    upload_node = r.json()["Result"]["InnerUploadAddress"]["UploadNodes"][0]
                  ~~~~~~~~^^^^^^^^^^
KeyError: 'Result'`

**Comment by MarcoLavoro** [comment]
any update on this?

**Comment by NinhXNT** [comment]
Make you use the correct session 
and also check the UA from your cookie.
![Screenshot 2024-06-29 183625](https://github.com/546200350/TikTokUploder/assets/143258827/3ae14011-ef07-42d3-b4d0-e7ab0edc7de6)

![image](https://github.com/546200350/TikTokUploder/assets/143258827/931484ba-bd45-433c-b98e-7c1d0b033b1d)

**Comment by guillaume-gex** [comment]
I have the same error :     
upload_node = r.json()["Result"]["InnerUploadAddress"]["UploadNodes"][0]
                  ~~~~~~~~^^^^^^^^^^
KeyError: 'Result'

I am trying my best to pass it but I cannot... I have the right session_ID from the cookie etc... as far as I can see... printing the r json:
{'ResponseMetadata': {'RequestId': '20240811210833FA74C5E04793BA2F97BB', 'Action': 'ApplyUploadInner', 'Version': '2020-11-19', 'Service': 'vod', 'Region': 'us-east-1', 'Error': {'CodeN': 100026, 'Code': 'InvalidSecretToken', 'Message': 'Invalid secret token, msg: %s.'}}}
Traceback (most recent call last):

Any idea / help please ? thank you
